services:
  # Django service
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: gunicorn --bind 0.0.0.0:8000 todo.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/static
    expose:
      - "8000"

    depends_on:
      - db
    environment:
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: securepassword
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - frontend
      - backend

  # PostgreSQL service
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend


  # Nginx service (Reverse Proxy)
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - frontend
      - backend

volumes:
  postgres_data:
  static_volume:

networks:
  frontend:
  backend:
    driver: bridge
