services:
  # Django service
  django:
    image: cadams654/cd-ci-final-project:latest
    container_name: django
    platform: linux/amd64 
    command: gunicorn --bind 0.0.0.0:9000 todo.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/static
    expose:
      - "9000"  # Expose port 9000 internally
    ports:
      - "9000:9000"  # Map container port 9000 to host port 9000
    depends_on:
      - db
    environment:
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: securepassword
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - frontend
      - backend


  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: securepassword
    ports:
      - "4444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend


  # Nginx service (Reverse Proxy)
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile  # Keep this if you are building the Nginx image locally
    container_name: my-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "444:80"
    depends_on:
      - django
    networks:
      - frontend
      - backend

volumes:
  postgres_data:
  static_volume:

networks:
  frontend:
  backend:
    driver: bridge
