---

- name: Remove conflicting packages
  apt:
    name:
      - containerd
      - docker.io
    state: absent
    autoremove: yes

- name: Install other dependencies
  apt:
    name:
      - python3-pip
      - python3-venv
      - docker-compose
    state: present

- name: Ensure Docker service is started
  service:
    name: docker
    state: started
    enabled: yes

- name: Add the user to the Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes